// Dữ liệu ngân hàng và biểu lãi suất chuẩn hóa phục vụ Seed DB & Last-Known-Good Fallback

export interface MasterBank {
  id: string;
  code: string;
  name: string;
  short_name: string;
  slug: string;
  official_website: string;
  official_domain: string;
  logo: string;
  color: string;
  established_year: number;
  active: boolean;
}

export interface MasterRate {
  id: string;
  bank_id: string;
  currency: string;
  channel: "online" | "counter";
  term_value: number;
  term_unit: "day" | "month" | "year";
  interest_rate: number;
  payment_method: "maturity" | "monthly" | "quarterly" | "upfront";
  min_amount: number;
  max_amount?: number;
  customer_segment: string;
  note?: string;
  source_url: string;
  verified_at: string;
}

export const MASTER_BANKS: MasterBank[] = [
  {
    id: "vietcombank",
    code: "VCB",
    name: "Ngân hàng TMCP Ngoại thương Việt Nam",
    short_name: "Vietcombank",
    slug: "vietcombank",
    official_website: "https://vietcombank.com.vn",
    official_domain: "vietcombank.com.vn",
    logo: "/logo/vietcombank.png",
    color: "#00843D",
    established_year: 1963,
    active: true,
  },
  {
    id: "vietinbank",
    code: "CTG",
    name: "Ngân hàng TMCP Công thương Việt Nam",
    short_name: "VietinBank",
    slug: "vietinbank",
    official_website: "https://vietinbank.vn",
    official_domain: "vietinbank.vn",
    logo: "/logo/vietinbank.png",
    color: "#1A4480",
    established_year: 1988,
    active: true,
  },
  {
    id: "bidv",
    code: "BID",
    name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
    short_name: "BIDV",
    slug: "bidv",
    official_website: "https://bidv.com.vn",
    official_domain: "bidv.com.vn",
    logo: "/logo/bidv.png",
    color: "#004B87",
    established_year: 1957,
    active: true,
  },
  {
    id: "agribank",
    code: "AGR",
    name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
    short_name: "Agribank",
    slug: "agribank",
    official_website: "https://agribank.com.vn",
    official_domain: "agribank.com.vn",
    logo: "/logo/agribank.png",
    color: "#E31837",
    established_year: 1988,
    active: true,
  },
  {
    id: "techcombank",
    code: "TCB",
    name: "Ngân hàng TMCP Kỹ thương Việt Nam",
    short_name: "Techcombank",
    slug: "techcombank",
    official_website: "https://techcombank.com.vn",
    official_domain: "techcombank.com.vn",
    logo: "/logo/techcombank.png",
    color: "#ED1B24",
    established_year: 1993,
    active: true,
  },
  {
    id: "mbbank",
    code: "MBB",
    name: "Ngân hàng TMCP Quân đội",
    short_name: "MB Bank",
    slug: "mbbank",
    official_website: "https://mbbank.com.vn",
    official_domain: "mbbank.com.vn",
    logo: "/logo/mbbank.png",
    color: "#003A70",
    established_year: 1994,
    active: true,
  },
  {
    id: "vpbank",
    code: "VPB",
    name: "Ngân hàng TMCP Việt Nam Thịnh Vượng",
    short_name: "VPBank",
    slug: "vpbank",
    official_website: "https://vpbank.com.vn",
    official_domain: "vpbank.com.vn",
    logo: "/logo/vpbank.png",
    color: "#00A651",
    established_year: 1993,
    active: true,
  },
  {
    id: "acb",
    code: "ACB",
    name: "Ngân hàng TMCP Á Châu",
    short_name: "ACB",
    slug: "acb",
    official_website: "https://acb.com.vn",
    official_domain: "acb.com.vn",
    logo: "/logo/acb.png",
    color: "#0068B3",
    established_year: 1993,
    active: true,
  },
  {
    id: "sacombank",
    code: "STB",
    name: "Ngân hàng TMCP Sài Gòn Thương Tín",
    short_name: "Sacombank",
    slug: "sacombank",
    official_website: "https://sacombank.com.vn",
    official_domain: "sacombank.com.vn",
    logo: "/logo/sacombank.png",
    color: "#005BAA",
    established_year: 1991,
    active: true,
  },
  {
    id: "hdbank",
    code: "HDB",
    name: "Ngân hàng TMCP Phát triển TP.HCM",
    short_name: "HDBank",
    slug: "hdbank",
    official_website: "https://hdbank.com.vn",
    official_domain: "hdbank.com.vn",
    logo: "/logo/hdbank.png",
    color: "#EE1D23",
    established_year: 1990,
    active: true,
  },
  {
    id: "shb",
    code: "SHB",
    name: "Ngân hàng TMCP Sài Gòn - Hà Nội",
    short_name: "SHB",
    slug: "shb",
    official_website: "https://shb.com.vn",
    official_domain: "shb.com.vn",
    logo: "/logo/shb.png",
    color: "#F37023",
    established_year: 1993,
    active: true,
  },
  {
    id: "tpbank",
    code: "TPB",
    name: "Ngân hàng TMCP Tiên Phong",
    short_name: "TPBank",
    slug: "tpbank",
    official_website: "https://tpbank.com.vn",
    official_domain: "tpbank.com.vn",
    logo: "/logo/tpbank.png",
    color: "#782B90",
    established_year: 2008,
    active: true,
  },
  {
    id: "vib",
    code: "VIB",
    name: "Ngân hàng TMCP Quốc tế Việt Nam",
    short_name: "VIB",
    slug: "vib",
    official_website: "https://vib.com.vn",
    official_domain: "vib.com.vn",
    logo: "/logo/vib.png",
    color: "#004B87",
    established_year: 1996,
    active: true,
  },
  {
    id: "ocb",
    code: "OCB",
    name: "Ngân hàng TMCP Phương Đông",
    short_name: "OCB",
    slug: "ocb",
    official_website: "https://ocb.com.vn",
    official_domain: "ocb.com.vn",
    logo: "/logo/ocb.png",
    color: "#00913F",
    established_year: 1996,
    active: true,
  },
  {
    id: "msb",
    code: "MSB",
    name: "Ngân hàng TMCP Hàng Hải Việt Nam",
    short_name: "MSB",
    slug: "msb",
    official_website: "https://msb.com.vn",
    official_domain: "msb.com.vn",
    logo: "/logo/msb.png",
    color: "#FF6600",
    established_year: 1991,
    active: true,
  },
  {
    id: "seabank",
    code: "SSB",
    name: "Ngân hàng TMCP Đông Nam Á",
    short_name: "SeABank",
    slug: "seabank",
    official_website: "https://seabank.com.vn",
    official_domain: "seabank.com.vn",
    logo: "/logo/seabank.png",
    color: "#C4161C",
    established_year: 1994,
    active: true,
  },
  {
    id: "eximbank",
    code: "EIB",
    name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
    short_name: "Eximbank",
    slug: "eximbank",
    official_website: "https://eximbank.com.vn",
    official_domain: "eximbank.com.vn",
    logo: "/logo/eximbank.png",
    color: "#004B87",
    established_year: 1989,
    active: true,
  },
  {
    id: "lienvietpostbank",
    code: "LPB",
    name: "Ngân hàng TMCP Bưu điện Liên Việt (LPBank)",
    short_name: "LPBank",
    slug: "lienvietpostbank",
    official_website: "https://lienvietpostbank.com.vn",
    official_domain: "lienvietpostbank.com.vn",
    logo: "/logo/lpb.png",
    color: "#DA251D",
    established_year: 2008,
    active: true,
  },
  {
    id: "scb",
    code: "SCB",
    name: "Ngân hàng TMCP Sài Gòn",
    short_name: "SCB",
    slug: "scb",
    official_website: "https://scb.com.vn",
    official_domain: "scb.com.vn",
    logo: "/logo/scb.png",
    color: "#005BAA",
    established_year: 1992,
    active: true,
  },
  {
    id: "abbank",
    code: "ABB",
    name: "Ngân hàng TMCP An Bình",
    short_name: "ABBank",
    slug: "abbank",
    official_website: "https://abbank.vn",
    official_domain: "abbank.vn",
    logo: "/logo/abbank.png",
    color: "#00913F",
    established_year: 1993,
    active: true,
  },
  {
    id: "bacabank",
    code: "BAB",
    name: "Ngân hàng TMCP Bắc Á",
    short_name: "Bac A Bank",
    slug: "bacabank",
    official_website: "https://baca-bank.vn",
    official_domain: "baca-bank.vn",
    logo: "/logo/bacabank.png",
    color: "#C4161C",
    established_year: 1994,
    active: true,
  },
  {
    id: "namabank",
    code: "NAB",
    name: "Ngân hàng TMCP Nam Á",
    short_name: "Nam A Bank",
    slug: "namabank",
    official_website: "https://namabank.com.vn",
    official_domain: "namabank.com.vn",
    logo: "/logo/namabank.png",
    color: "#E5A823",
    established_year: 1992,
    active: true,
  },
  {
    id: "ncb",
    code: "NVB",
    name: "Ngân hàng TMCP Quốc Dân",
    short_name: "NCB",
    slug: "ncb",
    official_website: "https://ncb-bank.vn",
    official_domain: "ncb-bank.vn",
    logo: "/logo/ncb.png",
    color: "#004B87",
    established_year: 1995,
    active: true,
  },
  {
    id: "pvcombank",
    code: "PVC",
    name: "Ngân hàng TMCP Đại Chúng Việt Nam",
    short_name: "PVcomBank",
    slug: "pvcombank",
    official_website: "https://pvcombank.com.vn",
    official_domain: "pvcombank.com.vn",
    logo: "/logo/pvcombank.png",
    color: "#F37023",
    established_year: 2013,
    active: true,
  },
  {
    id: "kienlongbank",
    code: "KLB",
    name: "Ngân hàng TMCP Kiên Long",
    short_name: "Kienlongbank",
    slug: "kienlongbank",
    official_website: "https://kienlongbank.com",
    official_domain: "kienlongbank.com",
    logo: "/logo/kienlongbank.png",
    color: "#E31837",
    established_year: 1995,
    active: true,
  },
  {
    id: "pgbank",
    code: "PGB",
    name: "Ngân hàng TMCP Xăng dầu Petrolimex (BVBank)",
    short_name: "PG Bank",
    slug: "pgbank",
    official_website: "https://pgbank.com.vn",
    official_domain: "pgbank.com.vn",
    logo: "/logo/pgbank.png",
    color: "#005BAA",
    established_year: 1993,
    active: true,
  },
  {
    id: "vietabank",
    code: "VAB",
    name: "Ngân hàng TMCP Việt Á",
    short_name: "VietABank",
    slug: "vietabank",
    official_website: "https://vietabank.com.vn",
    official_domain: "vietabank.com.vn",
    logo: "/logo/vietabank.png",
    color: "#00843D",
    established_year: 2003,
    active: true,
  },
  {
    id: "vietbank",
    code: "VBB",
    name: "Ngân hàng TMCP Việt Nam Thương Tín",
    short_name: "Vietbank",
    slug: "vietbank",
    official_website: "https://vietbank.com.vn",
    official_domain: "vietbank.com.vn",
    logo: "/logo/vietbank.png",
    color: "#004B87",
    established_year: 2006,
    active: true,
  },
  {
    id: "saigonbank",
    code: "SGB",
    name: "Ngân hàng TMCP Sài Gòn Công Thương",
    short_name: "Saigonbank",
    slug: "saigonbank",
    official_website: "https://saigonbank.com.vn",
    official_domain: "saigonbank.com.vn",
    logo: "/logo/saigonbank.png",
    color: "#ED1B24",
    established_year: 1987,
    active: true,
  },
  {
    id: "baovietbank",
    code: "BVB",
    name: "Ngân hàng TMCP Bảo Việt",
    short_name: "BaoViet Bank",
    slug: "baovietbank",
    official_website: "https://baovietbank.vn",
    official_domain: "baovietbank.vn",
    logo: "/logo/baovietbank.png",
    color: "#F37023",
    established_year: 2008,
    active: true,
  },
];

// Baseline Rates được tạo dựa trên dữ liệu chuẩn hoá thực tế từ các ngân hàng
export const BASELINE_RATES: MasterRate[] = [
  // Vietcombank
  { id: "vcb-1-on", bank_id: "vietcombank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 1.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-3-on", bank_id: "vietcombank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 1.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-6-on", bank_id: "vietcombank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 2.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-12-on", bank_id: "vietcombank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-1-ct", bank_id: "vietcombank", currency: "VND", channel: "counter", term_value: 1, term_unit: "month", interest_rate: 1.5, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-3-ct", bank_id: "vietcombank", currency: "VND", channel: "counter", term_value: 3, term_unit: "month", interest_rate: 1.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-6-ct", bank_id: "vietcombank", currency: "VND", channel: "counter", term_value: 6, term_unit: "month", interest_rate: 2.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },
  { id: "vcb-12-ct", bank_id: "vietcombank", currency: "VND", channel: "counter", term_value: 12, term_unit: "month", interest_rate: 4.5, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietcombank.com.vn", verified_at: "2026-05-07" },

  // VietinBank
  { id: "vtb-1-on", bank_id: "vietinbank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 1.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietinbank.vn", verified_at: "2026-05-07" },
  { id: "vtb-3-on", bank_id: "vietinbank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 2.0, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietinbank.vn", verified_at: "2026-05-07" },
  { id: "vtb-6-on", bank_id: "vietinbank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 3.0, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietinbank.vn", verified_at: "2026-05-07" },
  { id: "vtb-12-on", bank_id: "vietinbank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vietinbank.vn", verified_at: "2026-05-07" },

  // BIDV
  { id: "bidv-1-on", bank_id: "bidv", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 1.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://bidv.com.vn", verified_at: "2026-05-07" },
  { id: "bidv-3-on", bank_id: "bidv", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 1.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://bidv.com.vn", verified_at: "2026-05-07" },
  { id: "bidv-6-on", bank_id: "bidv", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 2.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://bidv.com.vn", verified_at: "2026-05-07" },
  { id: "bidv-12-on", bank_id: "bidv", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://bidv.com.vn", verified_at: "2026-05-07" },

  // Agribank
  { id: "agb-1-on", bank_id: "agribank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 1.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://agribank.com.vn", verified_at: "2026-05-07" },
  { id: "agb-3-on", bank_id: "agribank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 1.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://agribank.com.vn", verified_at: "2026-05-07" },
  { id: "agb-6-on", bank_id: "agribank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 2.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://agribank.com.vn", verified_at: "2026-05-07" },
  { id: "agb-12-on", bank_id: "agribank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://agribank.com.vn", verified_at: "2026-05-07" },

  // Techcombank
  { id: "tcb-1-on", bank_id: "techcombank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.5, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://techcombank.com.vn", verified_at: "2026-05-07" },
  { id: "tcb-3-on", bank_id: "techcombank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 2.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://techcombank.com.vn", verified_at: "2026-05-07" },
  { id: "tcb-6-on", bank_id: "techcombank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 4.2, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://techcombank.com.vn", verified_at: "2026-05-07" },
  { id: "tcb-12-on", bank_id: "techcombank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://techcombank.com.vn", verified_at: "2026-05-07" },

  // MB Bank
  { id: "mbb-1-on", bank_id: "mbbank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://mbbank.com.vn", verified_at: "2026-05-07" },
  { id: "mbb-3-on", bank_id: "mbbank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 2.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://mbbank.com.vn", verified_at: "2026-05-07" },
  { id: "mbb-6-on", bank_id: "mbbank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 3.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://mbbank.com.vn", verified_at: "2026-05-07" },
  { id: "mbb-12-on", bank_id: "mbbank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://mbbank.com.vn", verified_at: "2026-05-07" },

  // VPBank
  { id: "vpb-1-on", bank_id: "vpbank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vpbank.com.vn", verified_at: "2026-05-07" },
  { id: "vpb-3-on", bank_id: "vpbank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 3.0, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vpbank.com.vn", verified_at: "2026-05-07" },
  { id: "vpb-6-on", bank_id: "vpbank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 4.3, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vpbank.com.vn", verified_at: "2026-05-07" },
  { id: "vpb-12-on", bank_id: "vpbank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 5.2, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://vpbank.com.vn", verified_at: "2026-05-07" },

  // ACB
  { id: "acb-1-on", bank_id: "acb", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.4, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://acb.com.vn", verified_at: "2026-05-07" },
  { id: "acb-3-on", bank_id: "acb", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 2.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://acb.com.vn", verified_at: "2026-05-07" },
  { id: "acb-6-on", bank_id: "acb", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 3.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://acb.com.vn", verified_at: "2026-05-07" },
  { id: "acb-12-on", bank_id: "acb", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 4.7, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://acb.com.vn", verified_at: "2026-05-07" },

  // HDBank
  { id: "hdb-1-on", bank_id: "hdbank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://hdbank.com.vn", verified_at: "2026-05-07" },
  { id: "hdb-3-on", bank_id: "hdbank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 3.1, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://hdbank.com.vn", verified_at: "2026-05-07" },
  { id: "hdb-6-on", bank_id: "hdbank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 4.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://hdbank.com.vn", verified_at: "2026-05-07" },
  { id: "hdb-12-on", bank_id: "hdbank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 5.4, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://hdbank.com.vn", verified_at: "2026-05-07" },

  // TPBank
  { id: "tpb-1-on", bank_id: "tpbank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.8, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://tpbank.com.vn", verified_at: "2026-05-07" },
  { id: "tpb-3-on", bank_id: "tpbank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 3.1, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://tpbank.com.vn", verified_at: "2026-05-07" },
  { id: "tpb-6-on", bank_id: "tpbank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 4.5, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://tpbank.com.vn", verified_at: "2026-05-07" },
  { id: "tpb-12-on", bank_id: "tpbank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 5.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://tpbank.com.vn", verified_at: "2026-05-07" },

  // SeABank
  { id: "sea-1-on", bank_id: "seabank", currency: "VND", channel: "online", term_value: 1, term_unit: "month", interest_rate: 2.9, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://seabank.com.vn", verified_at: "2026-05-07" },
  { id: "sea-3-on", bank_id: "seabank", currency: "VND", channel: "online", term_value: 3, term_unit: "month", interest_rate: 3.2, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://seabank.com.vn", verified_at: "2026-05-07" },
  { id: "sea-6-on", bank_id: "seabank", currency: "VND", channel: "online", term_value: 6, term_unit: "month", interest_rate: 4.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://seabank.com.vn", verified_at: "2026-05-07" },
  { id: "sea-12-on", bank_id: "seabank", currency: "VND", channel: "online", term_value: 12, term_unit: "month", interest_rate: 5.6, payment_method: "maturity", min_amount: 1000000, customer_segment: "individual", source_url: "https://seabank.com.vn", verified_at: "2026-05-07" },
];
